In [ ]:
import numpy as np

five_store = np.random.randint(100,10000,size=(5,30))
five_store_cumsum = five_store.cumsum(axis=1)
five_store_cumsum

array([[  9402,  13002,  22853,  32144,  37909,  39027,  43844,  45895,
         52528,  61028,  62805,  64903,  72934,  75260,  77064,  83801,
         93570,  94037, 100630, 104766, 113919, 117163, 121631, 129129,
        129959, 134773, 144746, 150893, 152945, 159389],
       [  9822,  18049,  24993,  31716,  37496,  46476,  54237,  58438,
         62304,  66428,  69141,  73398,  82806,  92555,  97234, 101838,
        107920, 113099, 115567, 118065, 118250, 124373, 126898, 133546,
        137020, 142213, 143188, 148639, 158130, 158530],
       [  2895,   7307,  15735,  20747,  26928,  28033,  36628,  36929,
         45632,  49277,  52676,  59658,  67788,  75051,  80145,  88469,
         88668,  94988,  98427, 103187, 107867, 111561, 114539, 116992,
        125913, 133775, 143113, 150832, 151930, 160524],
       [  6558,  12926,  22000,  25601,  30943,  34226,  36257,  45020,
         53978,  61486,  71212,  75916,  79648,  85644,  85938,  88929,
         98841, 105717, 107852, 114346, 120647, 124038, 124991, 125406,
        133222, 136956, 143183, 152828, 160737, 169169],
       [  9339,  16144,  17655,  20326,  30288,  36777,  42086,  49103,
         51905,  56328,  63603,  65377,  71199,  75064,  78449,  87182,
         90858,  94613,  96702,  99086, 108445, 116671, 121224, 127494,
        128237, 136565, 136828, 140643, 141508, 150586]])

## DataFrame

In [6]:
import pandas as pd 

five_store = pd.DataFrame(five_store_cumsum,
             columns=[f'第{day}天' for day in range(1,31)],
             index=['台北分店','新竹分店','台中分店','台南分店','高雄分店'])
new_df = five_store.T  #反過來
new_df

        台北分店    新竹分店    台中分店    台南分店    高雄分店
第1天     9402    9822    2895    6558    9339
第2天    13002   18049    7307   12926   16144
第3天    22853   24993   15735   22000   17655
第4天    32144   31716   20747   25601   20326
第5天    37909   37496   26928   30943   30288
第6天    39027   46476   28033   34226   36777
第7天    43844   54237   36628   36257   42086
第8天    45895   58438   36929   45020   49103
第9天    52528   62304   45632   53978   51905
第10天   61028   66428   49277   61486   56328
第11天   62805   69141   52676   71212   63603
第12天   64903   73398   59658   75916   65377
第13天   72934   82806   67788   79648   71199
第14天   75260   92555   75051   85644   75064
第15天   77064   97234   80145   85938   78449
第16天   83801  101838   88469   88929   87182
第17天   93570  107920   88668   98841   90858
第18天   94037  113099   94988  105717   94613
第19天  100630  115567   98427  107852   96702
第20天  104766  118065  103187  114346   99086
第21天  113919  118250  107867  120647  108445
第22天  117163  124373  111561  124038  116671
第23天  121631  126898  114539  124991  121224
第24天  129129  133546  116992  125406  127494
第25天  129959  137020  125913  133222  128237
第26天  134773  142213  133775  136956  136565
第27天  144746  143188  143113  143183  136828
第28天  150893  148639  150832  152828  140643
第29天  152945  158130  151930  160737  141508
第30天  159389  158530  160524  169169  150586

In [9]:
type(new_df['台北分店'])
new_df['台中分店']

第1天       2895
第2天       7307
第3天      15735
第4天      20747
第5天      26928
第6天      28033
第7天      36628
第8天      36929
第9天      45632
第10天     49277
第11天     52676
第12天     59658
第13天     67788
第14天     75051
第15天     80145
第16天     88469
第17天     88668
第18天     94988
第19天     98427
第20天    103187
第21天    107867
第22天    111561
第23天    114539
第24天    116992
第25天    125913
第26天    133775
第27天    143113
第28天    150832
第29天    151930
第30天    160524
Name: 台中分店, dtype: int64