### pd.concat([DataFrame, DataFrame ])  裡面資料格式是list[DataFrame, DataFrame...]

In [27]:
import os
import pandas as pd
from pandas import DataFrame

def merge_data(station_paths:list[str], info:str)->DataFrame:
    '''
    傳出所有的資料
    '''
    info_df = pd.read_csv(info)
    merge_datas = []
    for sta_path in station_paths:    #station_paths是一個list[str]
        station_df = pd.read_csv(sta_path)
        merge_df = pd.merge(station_df, info_df,how='left',left_on='staCode',right_on='stationCode')
        merge_datas.append(merge_df)
    return pd.concat(merge_datas)  # 合併成一個大DataFrame 並回傳


current_folder = os.getcwd()    #取得現在檔案路徑 str
stations_folder = os.path.join(current_folder,'stations')    #合併並取得stations絕對路徑 str
csv_abs_files = []
for filename in os.listdir(stations_folder):  #list[str]
    if '每日各站' in filename:
        csv_abs_files.append(os.path.join(stations_folder,filename))

info_path = os.path.join(stations_folder,'台鐵車站資訊.csv')  #取得 台鐵車站資訊.csv的絕對路徑  str


df = merge_data(csv_abs_files,info_path)
df1 = df[['trnOpDate','gateInComingCnt','gateOutGoingCnt','name','stationAddrTw','haveBike']]

## colums=[]

In [28]:
df1.columns = ['日期','進站人數','出戰人數','站名','地址','Ubike']   #直接照順序改欄位名稱
df1

,日期,進站人數,出戰人數,站名,地址,Ubike
0,20230101,8030,8241,基隆,基隆市仁愛區港西街5號,Y
1,20230101,1017,1326,三坑,基隆市仁愛區德厚里龍安街 206 號,Y
2,20230101,1400,1705,八堵,基隆市暖暖區八南里八堵路 142 號,Y
3,20230101,3558,4398,七堵,基隆市七堵區長興里東新街 2 號,Y
4,20230101,1509,1815,百福,基隆市七堵區堵南里明德三路 1 之 1 號,N
...,...,...,...,...,...,...
86547,20221231,3984,3893,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,Y
86548,20221231,92,115,海科館,基隆市中正區長潭里,N
86549,20221231,131,159,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),N
86550,20221231,494,426,四腳亭,新北市瑞芳區吉慶里中央路 65 號,N
86551,20221231,313,274,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,N

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406761 entries, 0 to 86551
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   日期      406761 non-null  int64
 1   進站人數    406761 non-null  int64
 2   出戰人數    406761 non-null  int64
 3   站名      406761 non-null  object
 4   地址      406761 non-null  object
 5   Ubike   406761 non-null  object
dtypes: int64(3), object(3)
memory usage: 21.7+ MB

## to_datetime()

In [30]:
df1['日期'] = pd.to_datetime(df1['日期'].astype(str))
df1

/tmp/ipykernel_34835/915278159.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['日期'] = pd.to_datetime(df1['日期'].astype(str))

,日期,進站人數,出戰人數,站名,地址,Ubike
0,2023-01-01,8030,8241,基隆,基隆市仁愛區港西街5號,Y
1,2023-01-01,1017,1326,三坑,基隆市仁愛區德厚里龍安街 206 號,Y
2,2023-01-01,1400,1705,八堵,基隆市暖暖區八南里八堵路 142 號,Y
3,2023-01-01,3558,4398,七堵,基隆市七堵區長興里東新街 2 號,Y
4,2023-01-01,1509,1815,百福,基隆市七堵區堵南里明德三路 1 之 1 號,N
...,...,...,...,...,...,...
86547,2022-12-31,3984,3893,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,Y
86548,2022-12-31,92,115,海科館,基隆市中正區長潭里,N
86549,2022-12-31,131,159,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),N
86550,2022-12-31,494,426,四腳亭,新北市瑞芳區吉慶里中央路 65 號,N
86551,2022-12-31,313,274,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,N

## map()  裡面放dict直接改

In [11]:
df1['Ubike'] = df1['Ubike'].map({'Y':1,'N':0})

/tmp/ipykernel_34835/1106581799.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Ubike'] = df1['Ubike'].map({'Y':1,'N':0})

In [12]:
df1

,日期,進站人數,出戰人數,站名,地址,Ubike
0,2023-01-01,8030,8241,基隆,基隆市仁愛區港西街5號,1
1,2023-01-01,1017,1326,三坑,基隆市仁愛區德厚里龍安街 206 號,1
2,2023-01-01,1400,1705,八堵,基隆市暖暖區八南里八堵路 142 號,1
3,2023-01-01,3558,4398,七堵,基隆市七堵區長興里東新街 2 號,1
4,2023-01-01,1509,1815,百福,基隆市七堵區堵南里明德三路 1 之 1 號,0
...,...,...,...,...,...,...
86547,2022-12-31,3984,3893,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號,1
86548,2022-12-31,92,115,海科館,基隆市中正區長潭里,0
86549,2022-12-31,131,159,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房),0
86550,2022-12-31,494,426,四腳亭,新北市瑞芳區吉慶里中央路 65 號,0
86551,2022-12-31,313,274,暖暖,基隆市暖暖區暖暖里暖暖街 51 號,0

## sort_values() 排序

In [15]:
df2 = df1.sort_values(by='日期')
df2

              日期   進站人數   出戰人數   站名                  地址  Ubike
118   2019-04-23   2516   2667   永康  臺南市永康區埔園里中山路 459 號      1
92    2019-04-23     19     21   源泉  彰化縣二水鄉合興村英義路 (無站房)      0
93    2019-04-23     70     63   濁水   南投縣名間鄉濁水村車站路 15 號      0
94    2019-04-23      8     12   龍泉  南投縣集集鎮隘寮村龍泉巷 (無站房)      0
95    2019-04-23    299    127   集集   南投縣集集鎮吳厝里民生路 75 號      0
...          ...    ...    ...  ...                 ...    ...
86455 2023-12-31  19617  16699   彰化    彰化縣彰化市長樂里三民路 1 號      1
86456 2023-12-31   1864   1532   花壇  彰化縣花壇鄉花壇村中正路 370 號      1
86457 2023-12-31   1315   1100   大村  彰化縣大村鄉過溝村福進路 100 號      0
86445 2023-12-31    781    778  頭家厝     臺中市潭子區頭張東路43巷8號      0
86608 2023-12-31    576    447   暖暖   基隆市暖暖區暖暖里暖暖街 51 號      0

[406761 rows x 6 columns]

## DataFrame.set_index() 欄位改為index

In [16]:
df3 = df2.set_index('日期')
df3

             進站人數   出戰人數   站名                  地址  Ubike
日期
2019-04-23   2516   2667   永康  臺南市永康區埔園里中山路 459 號      1
2019-04-23     19     21   源泉  彰化縣二水鄉合興村英義路 (無站房)      0
2019-04-23     70     63   濁水   南投縣名間鄉濁水村車站路 15 號      0
2019-04-23      8     12   龍泉  南投縣集集鎮隘寮村龍泉巷 (無站房)      0
2019-04-23    299    127   集集   南投縣集集鎮吳厝里民生路 75 號      0
...           ...    ...  ...                 ...    ...
2023-12-31  19617  16699   彰化    彰化縣彰化市長樂里三民路 1 號      1
2023-12-31   1864   1532   花壇  彰化縣花壇鄉花壇村中正路 370 號      1
2023-12-31   1315   1100   大村  彰化縣大村鄉過溝村福進路 100 號      0
2023-12-31    781    778  頭家厝     臺中市潭子區頭張東路43巷8號      0
2023-12-31    576    447   暖暖   基隆市暖暖區暖暖里暖暖街 51 號      0

[406761 rows x 5 columns]

In [17]:
def first_third(val:str)->str:
    return val[:3]
df3['地址'].map(first_third)

日期
2019-04-23    臺南市
2019-04-23    彰化縣
2019-04-23    南投縣
2019-04-23    南投縣
2019-04-23    南投縣
             ...
2023-12-31    彰化縣
2023-12-31    彰化縣
2023-12-31    彰化縣
2023-12-31    臺中市
2023-12-31    基隆市
Name: 地址, Length: 406761, dtype: object

In [18]:
df3['縣市'] = df3['地址'].map(lambda v:v[:3])

## index.strftime('格式)

In [21]:
df3["年度"] = df3.index.strftime('%Y')
df3["年月"] = df3.index.strftime('%Y-%m')

In [23]:
df4 = df3.reindex(columns=['縣市','年度','年月','站名','進站人數','出戰人數','Ubike'])
df4

             縣市    年度       年月   站名   進站人數   出戰人數  Ubike
日期
2019-04-23  臺南市  2019  2019-04   永康   2516   2667      1
2019-04-23  彰化縣  2019  2019-04   源泉     19     21      0
2019-04-23  南投縣  2019  2019-04   濁水     70     63      0
2019-04-23  南投縣  2019  2019-04   龍泉      8     12      0
2019-04-23  南投縣  2019  2019-04   集集    299    127      0
...         ...   ...      ...  ...    ...    ...    ...
2023-12-31  彰化縣  2023  2023-12   彰化  19617  16699      1
2023-12-31  彰化縣  2023  2023-12   花壇   1864   1532      1
2023-12-31  彰化縣  2023  2023-12   大村   1315   1100      0
2023-12-31  臺中市  2023  2023-12  頭家厝    781    778      0
2023-12-31  基隆市  2023  2023-12   暖暖    576    447      0

[406761 rows x 7 columns]

In [24]:
df4.to_csv('全台火車進出站資訊.csv')